### ISSUE TITLE
LocalManager() crashes due to missing CRBind.totalCount

### ISSUE THREAD

**Issue by LourensVeen** [vecma-project/QCG-PilotJob#137]
I'm using the LocalManager inside of an allocation:
```
(qcgpj_venv) lveen@node030:~$ python3
Python 3.6.0 (default, Feb  1 2017, 17:31:40) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from qcg.pilotjob.api.manager import LocalManager as QCGManager
>>> qcg_manager = QCGManager()
```
This crashes with the following error:
```
--- Logging error ---
Traceback (most recent call last):
  File "/cm/shared/package/python/3.6.0/lib/python3.6/logging/__init__.py", line 987, in emit
    msg = self.format(record)
  File "/cm/shared/package/python/3.6.0/lib/python3.6/logging/__init__.py", line 833, in format
    return fmt.format(record)
  File "/cm/shared/package/python/3.6.0/lib/python3.6/logging/__init__.py", line 570, in format
    record.message = record.getMessage()
  File "/cm/shared/package/python/3.6.0/lib/python3.6/logging/__init__.py", line 333, in getMessage
    msg = msg % self.args
  File "/home/lveen/qcgpj_venv/lib/python3.6/site-packages/qcg/pilotjob/resources.py", line 636, in __str__
    return header + '\n'.join([str(node) for node in self._nodes])
  File "/home/lveen/qcgpj_venv/lib/python3.6/site-packages/qcg/pilotjob/resources.py", line 636, in <listcomp>
    return header + '\n'.join([str(node) for node in self._nodes])
  File "/home/lveen/qcgpj_venv/lib/python3.6/site-packages/qcg/pilotjob/resources.py", line 301, in __str__
    ', CR ({})'.format(self.str_crs) if self.crs else '')
  File "/home/lveen/qcgpj_venv/lib/python3.6/site-packages/qcg/pilotjob/resources.py", line 279, in str_crs
    self._crs.items()])
  File "/home/lveen/qcgpj_venv/lib/python3.6/site-packages/qcg/pilotjob/resources.py", line 278, in <listcomp>
    return ', '.join(['{} - {} ({} used))'.format(crtype.name, cr.totalCount, cr.used) for crtype, cr in
AttributeError: 'CRBind' object has no attribute 'totalCount'
Call stack:
  File "<stdin>", line 1, in <module>
  File "/home/lveen/qcgpj_venv/lib/python3.6/site-packages/qcg/pilotjob/api/manager.py", line 715, in __init__
    self.qcgpm_process.start()
  File "/cm/shared/package/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/cm/shared/package/python/3.6.0/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/cm/shared/package/python/3.6.0/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/cm/shared/package/python/3.6.0/lib/python3.6/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/cm/shared/package/python/3.6.0/lib/python3.6/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
  File "/cm/shared/package/python/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/lveen/qcgpj_venv/lib/python3.6/site-packages/qcg/pilotjob/service.py", line 613, in run
    self.service = QCGPMService(self.args)
  File "/home/lveen/qcgpj_venv/lib/python3.6/site-packages/qcg/pilotjob/service.py", line 289, in __init__
    self._setup_direct_manager(self._args.parent)
  File "/home/lveen/qcgpj_venv/lib/python3.6/site-packages/qcg/pilotjob/service.py", line 323, in _setup_direct_manager
    self._manager = DirectManager(self._tracer, self._conf, parent_manager)
  File "/home/lveen/qcgpj_venv/lib/python3.6/site-packages/qcg/pilotjob/manager.py", line 471, in __init__
    _logger.info('available resources: %s', self.resources)
Message: 'available resources: %s'
Arguments: (<qcg.pilotjob.resources.Resources object at 0x2aaabad80da0>,)
```
Looking at the code, I think Python is correct that `CRBind` has no attribute `totalCount`. I'm not sure what's intended here though. I've tried a couple of older versions of QCG-PJ, but those fail in the same way.

If I run this on the login node (of the DAS-5 cluster I'm using) there is no error, so it seems it gets triggered only if you're inside a Slurm allocation.

**Comment by paulmelis** [comment]
Running into the same issue, also within a SLURM allocation

**Comment by pkopta** [comment]
Hi all, sorry for such late response. The bug should be fixed in #144

**Comment by LourensVeen** [comment]
Yep, I can confirm that that patch works (applied against the current latest release, I didn't try the develop branch from git).

It seems to be hanging now when starting the agents, so there's another issue on this machine, but I'll make a separate issue for that once I have a better idea of what the problem is.

Do you prefer to leave this issue open until the fix is released, or shall we close it?

**Comment by pkopta** [comment]
Let's close it and create a new one for the hanging issue.

**Comment by LourensVeen** [comment]
Okay, thanks for fixing this one!
