### ISSUE TITLE
EasyVVUQ/QCG-PJ interface: issues in submission of 1000 jobs

### ISSUE THREAD

**Issue by jlakhlili** [vecma-project/QCG-PilotJob#40]
It concerns a test using slurm that performs 1000 samples: 
https://github.com/vecma-project/EasyVVUQ-QCGPJ/blob/dev/tests/test_qmc_inter.py#L106

In this test, 1000 encode_task and 1000 execute_task are submitted to the manager. Even if the completion of all PJ tasks is done (`wait4all` and `finish` are executed),  just 528 encode_task and 494 were really performed. Here is the log ouput of the execution:

> Running in directory: /marconi/home/userexternal/jlakhlil/workspace/easyVVUQ-QCGPJ/tests_JL
> Initializing Campaign
> QCG - Pilot Job: Initialisation
> manager process created
> manager process started
> got manager configuration: {'zmq_addresses': ['tcp://0.0.0.0:9470']}
> manager zmq iface address: tcp://0.0.0.0:9470
> log file set to /marconi_scratch/userexternal/jlakhlil/EasyVVUQ_Campaign_kukkzxvl/.qcgpj-cx8ty607/api.log
> Available resources:
> {'totalNodes': 1, 'totalCores': 48, 'usedCores': 0, 'freeCores': 48}
> Starting submission of tasks to QCG Pilot Job Manager
> Wait for completion of all PJ tasks
> Syncing state of campaign after execution of PJ
> Collating results

In the Campaign directory, we are waiting for the creation of 1000 run folders. But, When I check, just 528 are created. The `collater` will go through all folders, but it finds less. Here is the error output:

> Traceback (most recent call last):
>   File "test_cooling_pj_sl.py", line 179, in <module>
>     my_campaign.collate()
>   File "/marconi/home/userexternal/jlakhlil/.local/lib/python3.6/site-packages/easyvvuq-0.3.1+168.g5279636-py3.6.egg/easyvvuq/campaign.py", line 667, in collate
>   File "/marconi/home/userexternal/jlakhlil/.local/lib/python3.6/site-packages/easyvvuq-0.3.1+168.g5279636-py3.6.egg/easyvvuq/collate/aggregate_samples.py", line 76, in collate
>   File "/marconi/home/userexternal/jlakhlil/.local/lib/python3.6/site-packages/easyvvuq-0.3.1+168.g5279636-py3.6.egg/easyvvuq/decoders/simple_csv.py", line 77, in sim_complete
>   File "/marconi/home/userexternal/jlakhlil/.local/lib/python3.6/site-packages/easyvvuq-0.3.1+168.g5279636-py3.6.egg/easyvvuq/decoders/simple_csv.py", line 71, in _get_output_path
> RuntimeError: Run directory does not exist: /marconi_scratch/userexternal/jlakhlil/EasyVVUQ_Campaign_kukkzxvl/runs/Run_529

The code was executed just for the first 494 samples: the `decoder` will crush also because there are no results in the folder Run_495 and more.. 

Please find attached the **qcgpjm**  folder for the PJ outputs.
[qcgpjm_1000.zip](https://github.com/vecma-project/QCG-PilotJob/files/3781013/qcgpjm_1000.zip)

PS. This test was done twice. With the cooling model (cf. GitHub link above) and with fusion application in Marconi Cluster using 1 node (48 cores).

**Comment by jlakhlili** [comment]
I did new tests with 1000 and  10000 samples using **issue_37_monitoring** branch and it works.
Thanks!
