### ISSUE TITLE
zmq.error.ZMQError: Too many open files

### ISSUE THREAD

**Issue by NicolasMonnier** [vecma-project/QCG-PilotJob#41]
I was trying to launch around 2.000 jobs but from the 1022th job to the last one, the jobs failed with the following error message :
 
`zmq.error.ZMQError: Too many open files`

For this test, I compiled everything from source, even libzmq. 

It appears that the default maximum sockets of libzmq is 1023. 
So I modified this default value in the libzmq source and compiled another time : 

https://github.com/zeromq/libzmq/blob/af86d93d5f9634c5f28664c667510b044f2a149c/include/zmq.h#L227

Setting this variable with a higher value **solved the problem**.

So If you have the same problem but didn't compile libzmq by yourself (I assume it's already installed on your cluster), contact your cluster admin.

**Comment by NicolasMonnier** [comment]
The full error message from service.log

`2019-11-08 16:01:11,060: failed to start job __api_client_1022
Traceback (most recent call last):
  File "/home_nfs_robin_ib/bmonniern/.local/lib/python3.6/site-packages/qcg/appscheduler/executionjob.py", line 163, in run
    await self.launch()
  File "/home_nfs_robin_ib/bmonniern/.local/lib/python3.6/site-packages/qcg/appscheduler/executionjob.py", line 300, in launch
    finish_cb=self.__finishCb)
  File "/home_nfs_robin_ib/bmonniern/.local/lib/python3.6/site-packages/qcg/appscheduler/launcher/launcher.py", line 117, in submit
    out_socket = self.zmq_ctx.socket(zmq.REQ)
  File "/home_nfs_robin_ib/bmonniern/.local/lib/python3.6/site-packages/zmq/sugar/context.py", line 146, in socket
    s = self._socket_class(self, socket_type, **kwargs)
  File "/home_nfs_robin_ib/bmonniern/.local/lib/python3.6/site-packages/zmq/_future.py", line 134, in __init__
    super(_AsyncSocket, self).__init__(context, socket_type, **kwargs)
  File "/home_nfs_robin_ib/bmonniern/.local/lib/python3.6/site-packages/zmq/sugar/socket.py", line 59, in __init__
    super(Socket, self).__init__(*a, **kw)
  File "zmq/backend/cython/socket.pyx", line 328, in zmq.backend.cython.socket.Socket.__init__ (zmq/backend/cython/socket.c:4035)
zmq.error.ZMQError: Too many open files
`

**Comment by pkopta** [comment]
Hi Nicolas,

The branches issue_37_monitoring and issue_39_perf_tools should have solved issue 'too many open files'. Let me know if it's not the case.

**Comment by pkopta** [comment]
solved in issue_37_monitoring
